import json
from dataclasses import dataclass, field
from pathlib import Path

SKIP_DIRS = {
    "node_modules", "dist", "build", ".next", "vendor", "__pycache__",
    ".git", ".svn", ".hg", "coverage", ".nyc_output", ".cache",
    ".turbo", ".vercel", ".netlify", "out", "target", "bin", "obj",
    ".tox", ".mypy_cache", ".pytest_cache", "venv", ".venv", "env",
}

BINARY_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".svg", ".bmp", ".webp",
    ".woff", ".woff2", ".ttf", ".eot", ".otf",
    ".mp3", ".mp4", ".wav", ".avi", ".mov",
    ".zip", ".tar", ".gz", ".rar", ".7z",
    ".pdf", ".doc", ".docx", ".xls", ".xlsx",
    ".pyc", ".pyo", ".so", ".dll", ".dylib", ".exe",
}

LOCK_FILES = {"package-lock.json", "yarn.lock", "pnpm-lock.yaml", "bun.lockb"}

LANGUAGE_MAP = {
    ".ts": "typescript", ".tsx": "typescript",
    ".js": "javascript", ".jsx": "javascript", ".mjs": "javascript", ".cjs": "javascript",
    ".py": "python",
    ".go": "go",
    ".rs": "rust",
    ".java": "java",
    ".rb": "ruby",
    ".php": "php",
    ".cs": "csharp",
    ".cpp": "cpp", ".cc": "cpp", ".c": "c", ".h": "c",
    ".swift": "swift",
    ".kt": "kotlin",
    ".css": "css", ".scss": "scss", ".less": "less",
    ".html": "html", ".htm": "html",
    ".json": "json",
    ".yaml": "yaml", ".yml": "yaml",
    ".md": "markdown",
    ".sql": "sql",
    ".sh": "shell", ".bash": "shell", ".zsh": "shell",
}

TEST_PATTERNS = {
    ".test.", ".spec.", "_test.", "_spec.",
    "test_", "spec_",
}

# Files/patterns that are machine-generated or vendored, not hand-written
GENERATED_MARKERS = {
    "auto-generated", "autogenerated", "do not edit",
    "generated by", "this file is generated", "@generated",
    "do not modify", "automatically generated",
    "this file was generated", "code generated by",
}

GENERATED_FILENAMES = {
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "bun.lockb",
    "database.types.ts", "schema.prisma",
    "introspection.ts",  # GraphQL
}

GENERATED_EXTENSIONS = {".map", ".d.ts", ".min.js", ".min.css"}

GENERATED_DIRS = {"migrations", "drizzle", "prisma/migrations", ".prisma"}

# Non-code extensions that shouldn't get code-quality heuristics (nesting, god-file, etc.)
NON_CODE_EXTENSIONS = {
    ".md", ".markdown", ".txt", ".rst",
    ".json", ".yaml", ".yml", ".toml", ".xml",
    ".csv", ".env", ".ini", ".cfg",
    ".lock",
    ".svg",  # SVG files are markup, not code logic
    ".css", ".scss", ".less",  # Stylesheets aren't code complexity
}

# Directories containing vendored/third-party code
VENDORED_DIRS = {"components/ui", "ui/primitives"}

MAX_FILES = 10_000


@dataclass
class ScannedFile:
    path: str
    extension: str
    language: str | None
    loc: int
    content: str
    is_test: bool
    is_generated: bool = False
    is_vendored: bool = False
    is_barrel: bool = False


SHADCN_CONTENT_MARKERS = {
    "components/ui/",        # imports from shadcn ui dir
    "@radix-ui/",            # radix primitives (shadcn foundation)
    "class-variance-authority",  # cva — shadcn's styling pattern
    "cn(",                   # shadcn's classname utility
}


@dataclass
class ScanResult:
    files: list[ScannedFile] = field(default_factory=list)
    total_files: int = 0
    total_loc: int = 0
    languages: dict[str, float] = field(default_factory=dict)
    primary_language: str = "unknown"
    package_json: dict | None = None
    has_readme: bool = False
    readme_content: str = ""
    has_lock_file: bool = False
    shadcn_components_dir: str | None = None


def _is_test_file(path: str) -> bool:
    name = Path(path).name.lower()
    parent = Path(path).parent.name.lower()
    if parent in {"test", "tests", "__tests__", "spec", "specs"}:
        return True
    return any(pattern in name for pattern in TEST_PATTERNS)


def _is_shadcn_component(content: str) -> bool:
    """Detect ShadCN vendored components by content markers."""
    markers_found = sum(1 for m in SHADCN_CONTENT_MARKERS if m in content)
    return markers_found >= 2


def _is_barrel_file(content: str) -> bool:
    """Detect barrel/index files that only re-export from other modules."""
    lines = [l.strip() for l in content.splitlines() if l.strip() and not l.strip().startswith('//')]
    if not lines:
        return False
    export_lines = sum(1 for l in lines if l.startswith('export ') and 'from' in l)
    return export_lines / len(lines) >= 0.7


def scan_repo(repo_path: Path) -> ScanResult:
    """Single-pass walk of the repo, collecting all metrics."""
    result = ScanResult()
    lang_loc: dict[str, int] = {}

    # Detect ShadCN — check for components.json at root
    shadcn_config = repo_path / "components.json"
    if shadcn_config.exists():
        try:
            config = json.loads(shadcn_config.read_text())
            if "ui.shadcn.com" in config.get("$schema", ""):
                # Extract the components dir (e.g. "@/components" -> "components")
                comp_alias = config.get("aliases", {}).get("components", "")
                result.shadcn_components_dir = comp_alias.replace("@/", "").replace("~/", "")
        except (json.JSONDecodeError, OSError):
            pass

    for item in _walk_files(repo_path):
        if result.total_files >= MAX_FILES:
            break

        rel_path = str(item.relative_to(repo_path))
        ext = item.suffix.lower()

        # Skip binaries
        if ext in BINARY_EXTENSIONS:
            continue

        # Track lock files
        if item.name in LOCK_FILES:
            result.has_lock_file = True

        # Try to read file
        try:
            content = item.read_text(errors="ignore")
        except (OSError, UnicodeDecodeError):
            continue

        loc = len(content.splitlines())
        language = LANGUAGE_MAP.get(ext)
        is_test = _is_test_file(rel_path)

        # Track package.json
        if item.name == "package.json" and item.parent == repo_path:
            try:
                result.package_json = json.loads(content)
            except json.JSONDecodeError:
                pass

        # Track README
        if item.name.lower().startswith("readme"):
            result.has_readme = True
            result.readme_content = content

        # Check if file extension matches generated patterns (e.g. .d.ts, .min.js)
        is_generated_ext = any(rel_path.endswith(g_ext) for g_ext in GENERATED_EXTENSIONS)
        # Check if any parent directory is a generated dir
        path_parts = rel_path.split('/')
        is_generated_dir = any(
            '/'.join(path_parts[i:i+len(gd.split('/'))]) == gd
            for gd in GENERATED_DIRS
            for i in range(len(path_parts))
        )
        is_generated = (
            item.name in GENERATED_FILENAMES
            or is_generated_ext
            or is_generated_dir
            or any(marker in content[:500].lower() for marker in GENERATED_MARKERS)
        )
        is_vendored = any(vdir in rel_path for vdir in VENDORED_DIRS)

        # ShadCN vendored component detection
        if not is_vendored and result.shadcn_components_dir and rel_path.startswith(result.shadcn_components_dir):
            # Files in the ShadCN components dir that use ShadCN patterns are vendored
            if ext in {".tsx", ".ts"} and _is_shadcn_component(content):
                is_vendored = True

        scanned = ScannedFile(
            path=rel_path,
            extension=ext,
            language=language,
            loc=loc,
            content=content,
            is_test=is_test,
            is_generated=is_generated,
            is_vendored=is_vendored,
        )

        # Detect barrel files (index.ts that just re-exports)
        if item.name in {"index.ts", "index.tsx", "index.js", "index.jsx"} and _is_barrel_file(content):
            scanned.is_barrel = True

        result.files.append(scanned)
        result.total_files += 1
        result.total_loc += loc

        if language:
            lang_loc[language] = lang_loc.get(language, 0) + loc

    total_code_loc = sum(lang_loc.values()) or 1
    result.languages = {
        lang: round(loc / total_code_loc, 2)
        for lang, loc in sorted(lang_loc.items(), key=lambda x: -x[1])
    }
    if result.languages:
        result.primary_language = next(iter(result.languages))

    return result


def _walk_files(root: Path):
    """Walk directory tree, skipping ignored directories."""
    try:
        entries = sorted(root.iterdir())
    except PermissionError:
        return

    for entry in entries:
        if entry.is_dir():
            if entry.name in SKIP_DIRS or entry.name.startswith("."):
                continue
            yield from _walk_files(entry)
        elif entry.is_file():
            yield entry
